<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5rzsqoI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5rzsqoI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5rzsqoI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5rzsqoI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5rzsqoI\App_KernelDevDebugContainer([
    'container.build_hash' => '5rzsqoI',
    'container.build_id' => '93f8013e',
    'container.build_time' => 1586364020,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5rzsqoI');
